# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('ai.djl', 'api', '0.31.0')
require_jar('ai.djl.huggingface', 'tokenizers', '0.31.0')
require_jar('ai.djl.pytorch', 'pytorch-engine', '0.31.0')
require_jar('ai.djl.pytorch', 'pytorch-model-zoo', '0.31.0')
require_jar('com.google.code.gson', 'gson', '2.11.0')
require_jar('org.logstash.plugins.filter.embeddings_generator', 'logstash-filter-embeddings_generator', '0.1.1')
